cookbook/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('recipes/', views.recipes, name='recipes'),
    path('recipes/details/<int:id>', views.details, name='details'),
]

recipes/models.py
from django.db import models

# TextChoices dla rodzaju kuchni:
class Cuisine(models.TextChoices):
    Polska = 'polska'
    Włoska = 'wloska'
    Tajska = 'tajska'
    Węgierska = 'wegierska'

# Utworzenie modelu dla alergenów.
class Allergen(models.Model):
    name = models.CharField(
        max_length=50, unique=True
    )
    number = models.CharField(
        max_length=2, unique=True
    )

    def __str__(self):
        return f"{self.number}. {self.name}"

# Utworzenie modelu głównego z przepisem.
class Recipe(models.Model):
    dish = models.CharField(
        max_length=50,
        help_text='Wpisz nazwę dania',
    )
    cuisine = models.CharField(
        max_length=50,
        choices=Cuisine.choices,
        help_text='Wybierz rodzaj kuchni',
    )
    ingredients = models.TextField(
        help_text='Wpisz składniki wraz z ilością, oddzielając je przecinkami (np. Mąka - 200g,Woda - 100ml,Sól - 1 łyczeczka)',
    )
    allergens = models.ManyToManyField(
        Allergen,
        blank=True,
        related_name='recipes',
    )
    preparation_time = models.IntegerField(
        default=0,
        help_text='Wpisz czas przygotowania w minutach',
    )
    cooking_time = models.IntegerField(
        default=0,
        help_text='Wpisz czas wykonania przepisu w minutach',
    )
    image = models.ImageField(
        upload_to='recipes/',
        null=True,
        blank=True,
    )
    instructions_template = models.CharField(
        max_length=100,
        blank=True, null=True,
    )

    def __str__(self):
        return self.dish
    
    def get_ingredients_list(self):
        list = []
        for i in self.ingredients.split(','):
            list.append(i)
        return list

recipes/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Recipe

def recipes(request):
    myrecipes = Recipe.objects.all().order_by('id').values()
    template = loader.get_template('all_recipes.html')
    context = {
        'myrecipes': myrecipes,
    }
    return HttpResponse(template.render(context, request))

def details(request, id):
    myrecipe = Recipe.objects.get(id=id)
    template = loader.get_template('details.html')
    context = {
        'myrecipe': myrecipe,
    }
    return HttpResponse(template.render(context, request))

def main(request):
    template = loader.get_template('main.html')
    return HttpResponse(template.render())

recipes/templates/all_recipes.html
{% extends "master.html" %}

{% block title %}
  Lista przepisów
{% endblock %}


{% block content %}
{% load static %}
<div class="recipes">
    <br /><br /><br />

    <h1>Przepisy</h1>

    <ul>
      {% for x in myrecipes %}
      <a href="details/{{ x.id }}">
        <li class="recipe-list"> 
          {% if x.image %}
            <img src='/media/{{ x.image }}' alt="{{ x.dish }}">
          {% else %}
            <img src="{% static 'img/default.jpg' %}">
          {% endif %}
            <h2>{{ x.dish }}</h2>
        </li>
      </a>
      {% endfor %}
    </ul>
</div>
{% endblock %}

recipes/templates/details.html
{% extends "master.html" %}

{% block title %}
  {{ myrecipe.dish}}
{% endblock %}


{% block content %}
  {% load static %}
  <div class="mycard">
    <h1>{{ myrecipe.dish }}</h1>
    {% if myrecipe.image %}
      <img class="main-img" src='/media/{{ myrecipe.image }}' alt="{{ myrecipe.dish }}">
    {% else %}
      <img class="main-img" src="{% static 'img/default.jpg' %}">
    {% endif %}
    

    <h4>Kuchnia: {{ myrecipe.get_cuisine_display }}</h4>
    <h4>Alergeny: 
      {% for x in myrecipe.allergens.all %}
        {{ x.number }}{% if not forloop.last %}, {% endif %}
      {% empty %}
        Brak alergenów
      {% endfor %}
      <img src="{% static 'img/small_allergens.jpg' %}" alt="Miniaturka alergenów" class="small-img" onclick="toggleImage()">
    </h4>
    <img src="{% static 'img/allergens.jpg' %}" alt="Legenda alergenów" class="large-img" id="largeImage">
    <script>
      function toggleImage() {
          var img = document.getElementById("largeImage");
          if (img.classList.contains("active")) {
              img.classList.remove("active");
          } else {
              img.classList.add("active");
          }
      }
      document.getElementById("largeImage").addEventListener("click", function() {
          this.classList.remove("active");
      });
    </script>

    <h4>Czas przygotowania: {{ myrecipe.preparation_time }} min</h4>
    <h4>Czas gotowania/pieczenia/smażenia: {{ myrecipe.cooking_time }} min</h4>
    <br />

    <h2>Składniki:</h2>
      <ul>
        {% for x in myrecipe.get_ingredients_list %}
          <li>{{ x }}</li>
        {% endfor %}
      </ul>
    <br />

    <h2>Wykonanie:</h2>
      {% if myrecipe.instructions_template %}
        {% include myrecipe.instructions_template %}
      {% else %}
        <p>Brak instrukcji dla tego przepisu.</p>
      {% endif %}
    <br />
    
    <h2>SMACZNEGO!</h2>
  </div>
  <h1 style="color: black; text-align: center;">Spróbuj innych <a href="/recipes">Przepisów</a></h1>
{% endblock %}

recipes/templates/instructions/gulasz.html
<ul>
  <li>Użyj 800-1000 g łopatki wieprzowej (może być szynka lub mix szynki z karkówką 1:1). Pokrój na kawałki 2x2 cm.</li>
  <li>Dodaj 2 łyżki słodkiej papryki, 0,5 łyżeczki soli, 0,5 łyżeczki pieprzu, szczyptę chili. Obierz 4 ząbki czosnku (lub 1 łyżka suszonego), przepuść przez praskę, wymieszaj z mięsem.</li>
  <li>Rozgrzej głęboką patelnię, roztop 20 g smalcu. Podsmażaj mięso 25 minut na średnio-wysokim ogniu bez przykrycia, mieszając co jakiś czas.</li>
  <li>Przygotuj 2-3 cebule (lub 1 duży por), 2 marchewki, 2 czerwone papryki (można zamienić 1 na żółtą/pomarańczową). Pokrój cebulę w piórka, marchew w półplasterki, paprykę w kawałki.</li>
  <li>Rozgrzej drugą patelnię, roztop 50 g smalcu. Podsmaż cebulę 5 minut, dodaj marchew, smaż 15 minut na niskim ogniu bez przykrycia, mieszając co chwilę. Dodaj paprykę, smaż 10 minut.</li>
  <li>Przenieś warzywa do mięsa, wlej 500 ml bulionu. Gotuj 20 minut na małym ogniu bez przykrycia.</li>
  <li>Dodaj 2-3 łyżki koncentratu (lub przecier/świeże pomidory dla rzadszej konsystencji). Opcjonalnie zagęść 1 łyżką skrobi ziemniaczanej rozpuszczonej w wodzie/bulionie, gotuj 1 minutę.</li>
  <li>Skontroluj smak, dodaj sól, pieprz lub chili wg uznania.</li>
</ul>
<h3>Podanie:</h3>
<ul>
  <li>Podawaj z pieczywem, ogórkiem kiszonym, kaszą (gryczaną, pęczak, kuskus), tłuczonymi ziemniakami, kopytkami, kluskami śląskimi lub surówką z kapusty.</li>
</ul>

recipes/templates/instructions/k_schabowy.html
<ul>
  <li>Połóż na blacie ściereczkę, na niej deskę, ubij kotlety do 7 mm.</li>
  <li>Posyp solą i pieprzem.</li>
  <li>Zanurz w jajku, obtocz w bułce tartej.</li>
  <li>Smaż na smalcu po 2 min na stronę na złoty kolor.</li>
  <li>Usuń resztki bułki po każdej serii, dodaj smalec.</li>
</ul>
<h3>Podanie:</h3>
<ul>
  <li>Kotlety podajemy z gotowanymi ziemniakami, kopytkami czy też z kluskami śląskimi.</li>
  <li>Dodatkowo świetnie się nada surówka z białej kapusty lub ogórki małosolne.</li>
</ul>

recipes/templates/instructions/lazania.html
<h3>Farsz:</h3>
<ul>
  <li>Zmiel łopatkę. Podsmaż na oleju (10 min).</li>
  <li>Dodaj posiekaną cebulę i czosnek, smaż 5 min.</li>
  <li>Pieczarki pokrój, podsmaż na oleju, dodaj do mięsa.</li>
  <li>Wlej przecier i koncentrat, dopraw przyprawami, gotuj 15 min.</li>
</ul>
<h3>Sos śmietanowy:</h3>
<ul>
  <li>Wymieszaj śmietanę z mlekiem.</li>
</ul>
<h3>Sery:</h3>
<ul>
  <li>Zetrzyj mozzarellę i Gouda, wymieszaj.</li>
</ul>
<h3>Składanie:</h3>
<ul>
  <li>Rozgrzej piekarnik do 180°C.</li>
  <li>W formie: warstwa farszu, 4 płaty makaronu, farsz, sos, ser. Powtórz 2 razy. Na wierzch: makaron, sos, ser.</li>
</ul>
<h3>Pieczenie:</h3>
<ul>
  <li>Piecz 30-40 min, aż ser się zarumieni. Odstaw na 5 min.</li>
</ul>
<h3>Podanie:</h3>
<ul>
  <li>Porcje kroimy nożem i podajemy na talerzach.</li>
  <li>Opcjonalnie: posyp świeżą bazylią lub natką pietruszki, jeśli masz pod ręką.</li>
</ul>

recipes/templates/instructions/salatka_papaja.html
<ul>
  <li>W moździerzu rozgnieć chili, cukier, czosnek oraz łyżkę orzechów ziemnych.</li>
  <li>Pokrój kawałki czosnku i chili tak, by były wyraźnie wyczuwalne.</li>
  <li>Dodaj jeden plaster papai i rozetrzyj. Wlej sos rybny, sok z limonki oraz wodę, a następnie dokładnie wymieszaj.</li>
  <li>Pokrój papaję, ogórka i marchewkę.</li>
  <li>Do sosu wrzuć ogórka i marchewkę, delikatnie je ugniatając. Na sam koniec dodaj papaję. Jeśli jest zielona i niedojrzała – taka powinna być w tej sałatce – lekko poubijaj boki pasków, unikając zrobienia papki.</li>
  <li>Na koniec dodaj połówki pomidorków koktajlowych i dokładnie wymieszaj, aby wszystkie składniki przeszły sosem. Wierzch sałatki oprósz grubo posiekanymi orzechami ziemnymi, posiekanym chili oraz natką pietruszki.</li>
</ul>

recipes/templates/instructions/zurek.html
<ul>
  <li>Użyj 3 kiełbasy białe parzonej (ok. 330 g), resztę odłóż do innego dania.</li>
  <li>Pokrój 350 g surowego, wędzonego boczku w kostkę, podsmaż 5-10 minut, aż tłuszcz się wytopi i boczek się zarumieni.</li>
  <li>Dodaj pokrojone w plasterki (do 1 cm) kiełbasy, smaż 5 minut.</li>
  <li>Wlej 1 l gorącego bulionu warzywnego (może być więcej), dodaj 1 łyżkę majeranku, 2 ziarna ziela angielskiego, 1 liść laurowy, 1 ząbek czosnku. Przykryj, gotuj 10 minut na małym ogniu.</li>
  <li>Dodaj 1 łyżkę tartego chrzanu i 300-500 ml zakwasu żytniego (wcześniej wymieszanego na jednolity płyn). Gotuj bez przykrycia 2 minuty, aż zgęstnieje. Sprawdź smak.</li>
  <li>Dodaj 3 łyżki śmietanki 30% lub 36% (bez hartowania) lub wymieszaj kwaśną śmietanę 18% z odrobiną żurku przed dodaniem. Opcjonalnie pominąć.</li>
</ul>
<h3>Podanie:</h3>
<ul>
  <li>Serwuj z jajkami na twardo, twarogiem, ciemnym pieczywem lub tłuczonymi ziemniakami z cebulką.</li>
</ul>

recipes/templates/main.html
{% extends "master.html" %}

{% block title %}
  Internetowa Książka Kucharska
{% endblock %}


{% block content %}
<div class="main">
  <br /><br /><br /><br />
  <h1>Najlepsze dania oraz ciasta - zapraszam!</h1>
  <br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

  <ul>
    <li><a href="recipes/"><h2>Dania</h2></a></li>
    <li><a href=""><h2>Ciasta(in progress)</h2></a></li>
  </ul>
</div>
{% endblock %}

recipes/templates/master.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static 'mystyles.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div class="topnav">
  <a href="/">HOME</a>
</div>

{% block content %}
{% endblock %}

</body>
</html>